### ISSUE TITLE
I found an error, and when I have mounted an adapter, it shows the following message

### ISSUE THREAD

**Issue by cn-kali-team** [realgam3/requests-raw#3]
The ssl3httpadapter is a custom adapter

```python
session = requests.session()
session.mount('https://', Ssl3HttpAdapter())
```
- I found an error, and when I have mounted an adapter, it shows the following message
```
maximum recursion depth exceeded while calling a Python object      
Traceback (most recent call last):       
  File "/my/requests/sessions.py", line 590, in post         
    return self.request('POST', url, data=data, json=json, **kwargs)         
  File "/my/requests_raw/__init__.py", line 29, in __request 
    return _request(self, method, url, *args, **kwargs) 
  File "/my/requests_raw/__init__.py", line 29, in __request 
    return _request(self, method, url, *args, **kwargs) 
  File "/my/requests_raw/__init__.py", line 29, in __request 
    return _request(self, method, url, *args, **kwargs) 
  [Previous line repeated 988 more times]
  File "/my/requests_raw/__init__.py", line 25, in __request 
    if not getattr(self, "_raw_adapter_mounted", False):
RecursionError: maximum recursion depth exceeded while calling a Python object  
```

**Comment by cn-kali-team** [comment]
After I delete the automatic monkey patch, it works successfully

**Comment by realgam3** [comment]
> After I delete the automatic monkey patch, it works successfully

Thank you :)
I will check it out and fix it.

**Comment by realgam3** [comment]
@cn-kali-team can you help me with the reproduction?

**Comment by cn-kali-team** [comment]
> @cn-kali-team can you help me with the reproduction?

Sorry, I can't reproduce the problem now. Maybe there is a bug in my code,

**Comment by realgam3** [comment]
thank you :)
if it pops again, reopen the issue

> > @cn-kali-team can you help me with the reproduction?
> 
> Sorry, I can't reproduce the problem now. Maybe there is a bug in my code,
