### ISSUE TITLE
Problem with redirects

### ISSUE THREAD

**Issue by JJK96** [realgam3/requests-raw#4]
I'm trying to request google.com using a raw request:

```
Python 3.9.5 (default, May  4 2021, 03:36:27)
[Clang 12.0.0 (clang-1200.0.32.29)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import requests_raw
>>> res = requests_raw.raw(url='https://google.com/', data=b"GET / HTTP/1.1\r\nHost: google.com\r\n\r\n")
Traceback (most recent call last):
  File "/usr/local/Cellar/python@3.9/3.9.5/Frameworks/Python.framework/Versions/3.9/lib/python3.9/http/client.py", line 969, in send
    self.sock.sendall(data)
  File "/usr/local/Cellar/python@3.9/3.9.5/Frameworks/Python.framework/Versions/3.9/lib/python3.9/ssl.py", line 1201, in sendall
    with memoryview(data) as view, view.cast("B") as byte_view:
TypeError: memoryview: a bytes-like object is required, not 'NoneType'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.9/site-packages/requests_raw/api.py", line 12, in raw
    return request(__title__, url, data=data, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/requests_raw/api.py", line 7, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/requests_raw/__init__.py", line 29, in __request
    return _request(self, method, url, *args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.9/site-packages/requests/sessions.py", line 677, in send
    history = [resp for resp in gen]
  File "/usr/local/lib/python3.9/site-packages/requests/sessions.py", line 677, in <listcomp>
    history = [resp for resp in gen]
  File "/usr/local/lib/python3.9/site-packages/requests/sessions.py", line 237, in resolve_redirects
    resp = self.send(
  File "/usr/local/lib/python3.9/site-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
  File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 394, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/local/lib/python3.9/site-packages/urllib3/connection.py", line 234, in request
    super(HTTPConnection, self).request(method, url, body=body, headers=headers)
  File "/usr/local/Cellar/python@3.9/3.9.5/Frameworks/Python.framework/Versions/3.9/lib/python3.9/http/client.py", line 1253, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/local/Cellar/python@3.9/3.9.5/Frameworks/Python.framework/Versions/3.9/lib/python3.9/http/client.py", line 1299, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/local/lib/python3.9/site-packages/requests_raw/connection.py", line 94, in endheaders
    self.send(message_body)
  File "/usr/local/Cellar/python@3.9/3.9.5/Frameworks/Python.framework/Versions/3.9/lib/python3.9/http/client.py", line 975, in send
    raise TypeError("data should be a bytes-like object "
TypeError: data should be a bytes-like object or an iterable, got <class 'NoneType'>
>>>
```

When checking the result in my proxy I see that the following request and response have been sent:

```
GET / HTTP/1.1
Host: google.com
Connection: close


HTTP/1.1 301 Moved Permanently
Location: https://www.google.com/
Content-Type: text/html; charset=UTF-8
Date: Thu, 08 Jul 2021 14:26:35 GMT
Expires: Thu, 08 Jul 2021 14:26:35 GMT
Cache-Control: private, max-age=2592000
Server: gws
Content-Length: 220
X-XSS-Protection: 0
X-Frame-Options: SAMEORIGIN
Set-Cookie: CONSENT=PENDING+741; expires=Fri, 01-Jan-2038 00:00:00 GMT; path=/; domain=.google.com; Secure
P3P: CP="This is not a P3P policy! See g.co/p3phelp for more info."
Alt-Svc: h3=":443"; ma=2592000,h3-29=":443"; ma=2592000,h3-T051=":443"; ma=2592000,h3-Q050=":443"; ma=2592000,h3-Q046=":443"; ma=2592000,h3-Q043=":443"; ma=2592000,quic=":443"; ma=2592000; v="46,43"
Connection: close

<HTML><HEAD><meta http-equiv="content-type" content="text/html;charset=utf-8">
<TITLE>301 Moved</TITLE></HEAD><BODY>
<H1>301 Moved</H1>
The document has moved
<A HREF="https://www.google.com/">here</A>.
</BODY></HTML>
```

Following the redirection manually works:

```
res = requests_raw.raw(url='https://www.google.com/', data=b"GET / HTTP/1.1\r\nHost: www.google.com\r\n\r\n")
```

I don't understand enough about this library to debug this further, but it seems that there is a problem with handling redirects.

**Comment by realgam3** [comment]
Can you specify the version of requests_raw and the version of requests?

**Comment by JJK96** [comment]
```
pip freeze | grep requests
requests==2.25.1
requests-raw==1.0.0
```

**Comment by realgam3** [comment]
https://github.com/realgam3/requests-raw/commit/26e9e2f1a918d89e3f7e3a0508bcce249c79cb09
its a partial fix (it will not crash)

Because the issue is the response code 301, if you get 302 it will translate the request into get request but when you get 301 it will take the method and cookies, headers, etc and send the same request the only thing I can do is to return the original response code and let you fix the next request....

In a later commit I have changed the allow_redirect default option to false when sending raw requests.

**Comment by realgam3** [comment]
Version 2.0.0 released:
https://github.com/realgam3/requests-raw/releases/tag/v2.0.0
