### ISSUE TITLE
Hello, How can I read a non-standard response

### ISSUE THREAD

**Issue by cyal1** [realgam3/requests-raw#5]
Hello, How can I read a non-standard response

**Comment by realgam3** [comment]
> throwed

Can you add the request and the exception + stacktrace so I can find a solution for it?

**Comment by dem0ns** [comment]
run this command to fake a response:
```
echo 'HTTP/1.1 1x OK
Server: xxx
Content-Length: 6

011110' | nc -l 123
```

Code
```
import requests_raw

if __name__ == '__main__':
        x = requests_raw.raw("http://127.0.0.1:123", "GET / HTTP/1.1\r\n\r\n")
```



Exception:
`('Connection aborted.', BadStatusLine('HTTP/1.1 1x OK\n'))`

Traceback:
```
Traceback (most recent call last):
  File "/opt/homebrew/lib/python3.10/site-packages/urllib3/connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "/opt/homebrew/lib/python3.10/site-packages/urllib3/connectionpool.py", line 449, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/opt/homebrew/lib/python3.10/site-packages/urllib3/connectionpool.py", line 444, in _make_request
    httplib_response = conn.getresponse()
  File "/opt/homebrew/Cellar/python@3.10/3.10.9/Frameworks/Python.framework/Versions/3.10/lib/python3.10/http/client.py", line 1374, in getresponse
    response.begin()
  File "/opt/homebrew/Cellar/python@3.10/3.10.9/Frameworks/Python.framework/Versions/3.10/lib/python3.10/http/client.py", line 318, in begin
    version, status, reason = self._read_status()
  File "/opt/homebrew/Cellar/python@3.10/3.10.9/Frameworks/Python.framework/Versions/3.10/lib/python3.10/http/client.py", line 308, in _read_status
    raise BadStatusLine(line)
http.client.BadStatusLine: HTTP/1.1 1x OK
```

**Comment by realgam3** [comment]
Oh so this is actually an issue with httplib but I think o can fix it 😅
1x is the actual response code? Or 100/101?

**Comment by realgam3** [comment]
Please try: https://github.com/realgam3/requests-raw/tree/v1.1 :)

**Comment by realgam3** [comment]
Version 2.0.0 Released:
https://github.com/realgam3/requests-raw/releases/tag/v2.0.0
